### ISSUE TITLE
Wolfs!

### ISSUE THREAD

**Issue by matthew4444** [EpicSteve33/SurvivalGames#18]
working on a peyts plugin,ask if u need any help with plugin

**Comment by EpicSteve33** [comment]
well this is a ImgicalMine Plugin would any of your code help us?

**Comment by EpicSteve33** [comment]
@matthew4444 well if you can help us then you should do it, but the wolfs need to spawn with VIP+ players only in a match and if a player leaves the wolf needs to despawns and it needs to attack other players but if you can just get the wolf to spawn with ImagicalMine then I can do the rest

**Comment by EpicSteve33** [comment]
@matthew4444 just submit a pull request if you can get it to work and Ill merge it. I will not give you any perms btw because I have trust issues lel

**Comment by RedEnder** [comment]
Skrub

**Comment by EpicSteve33** [comment]
there you go ender XD

**Comment by RedEnder** [comment]
^ perfect!

**Comment by EpicSteve33** [comment]
Lel

**Comment by RedEnder** [comment]
@EpicSteve33 i looked at his code of Pets it spawns a Wolf but they dont follow players

**Comment by EpicSteve33** [comment]
Ik I've already seen the plugin but the issue is I can't even get them to spawn at all

**Comment by RedEnder** [comment]
Spawning them is so easy :P #Skrub

**Comment by EpicSteve33** [comment]
Shhhhh

**Comment by EpicSteve33** [comment]
Magiclel

**Comment by matthew4444** [comment]
they tp now

**Comment by matthew4444** [comment]
https://github.com/LostTeam/Pets

**Comment by matthew4444** [comment]
idk phpp butu can ask the team to help

**Comment by RedEnder** [comment]
@matthew4444 we need to move the wolfs on PlayerMoveEvent

**Comment by matthew4444** [comment]
ask them

**Comment by EpicSteve33** [comment]
@matthew4444 well im going to close this issue for now, maybe someday we will come back to this topic
